# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFehYFiBVAJNAXy9jT7BbLxi2oSO9y3J
"""

def get_user_input(prompt):
    while True:
        try:
            user_input = float(input(prompt))
            return user_input
        except ValueError:
            print("Please enter a valid number.")

def health_monitor():
    print("Welcome to the Health Monitor!")

    heart_rate = get_user_input("Enter your heart rate (beats per minute): ")
    blood_pressure_sys = get_user_input("Enter your systolic blood pressure (mmHg): ")
    blood_pressure_dia = get_user_input("Enter your diastolic blood pressure (mmHg): ")
    blood_sugar = get_user_input("Enter your blood sugar level (mg/dL): ")

    # Basic health assessment
    if heart_rate < 60:
        print("Your heart rate is below normal. You should consult a doctor.")
    elif heart_rate > 100:
        print("Your heart rate is above normal. You should consult a doctor.")

    if blood_pressure_sys > 140 or blood_pressure_dia > 90:
        print("Your blood pressure is high. You should consult a doctor.")

    if blood_sugar > 126:
        print("Your blood sugar level is high. You should consult a doctor.")

    print("Thank you for using the Health Monitor!")

if __name__ == "__main__":
    health_monitor()